language: node_js
node_js:
- '0.10'
env:
  global:
    secure: gwZrOCs5mOukCgPdj1nIqcIAUkw1X7Cy5aa7q1Ofl3mOYLVML7SFKOC8UpfqSDWd+9mLfClYOcy0brgYcco4D16ETWXCtm67WAH8YyOsr/IVKPVCKkwbG5dK0q/9ecjUa+im0/mBw+gprQUObYKADZI8EG6tPYjTTznqDU+ZXvU=
cache:
  directories:
  - node_modules
before_script:
- npm install -g grunt-cli
script:
- if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_BRANCH == master ]]; then npm run
  travis; else npm test; fi;
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: npm
  email: devsupport@familysearch.org
  api_key:
    secure: Okz5lNXjeqgiKHkEB/XEseglekEF8xPRVtOKJvJq5VjHuFekxaKep6cQDKnBTY1W5cm+2QUZB6sFjpdE0a5/En5aYOM9A2434gbxyg9diK7/2tGRJ+Jz0/b+jmWkb0KPg8pl8JwnLWH6QTS2rvCtiSiXj5JWUr2wP/1oCfdypRg=
  on:
    tags: true
    repo: FamilySearch/familysearch-javascript-sdk
